apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
  labels:
    app: intel-gpu-plugin
spec:
  selector:
    matchLabels:
      app: intel-gpu-plugin
  template:
    metadata:
      labels:
        app: intel-gpu-plugin
    spec:
#      initContainers:
#      - name: intel-gpu-initcontainer
#        image: intel/intel-gpu-initcontainer:devel
#        imagePullPolicy: IfNotPresent
#        securityContext:
#          readOnlyRootFilesystem: true
#          allowPrivilegeEscalation: false
#        volumeMounts:
#        - mountPath: /etc/kubernetes/node-feature-discovery/source.d/
#          name: nfd-source-hooks
      containers:
      - name: intel-gpu-plugin
        args:
        - "-v=5"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: gar-registry.caas.intel.com/virtiot/intel-kmsg-plugin:devel
        #image: intel/intel-gpu-plugin:devel
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: true
          privileged: true
        volumeMounts:
        - name: devfs
          mountPath: /dev/kmsg
          readOnly: true
#        - name: sysfs
#          mountPath: /sys/class/drm
#          readOnly: true
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: devfs
        hostPath:
          path: /dev/kmsg
#      - name: sysfs
#        hostPath:
#          path: /sys/class/drm
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: nfd-source-hooks
        hostPath:
          path: /etc/kubernetes/node-feature-discovery/source.d/
          type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/arch: amd64
